platform :ios, '9.0'

target 'MelodySkyChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MelodySkyChat
    # pod 'Stellar', :git => 'https://github.com/AugustRush/Stellar.git'
end
